---
title: "**Male courtship behaviour - aDN > TNT - wing vacillation**"
author: "Aaron M. Allen"
date: "10 March 2020"
output: html_notebook
---

<br/>
<br/>

# **Setup**

```{r message=FALSE}
library("tidyverse")
library("ggpubr")
library("zoo")
setwd("/mnt/LocalData/behaviour/aDN/aDN_behaviour")
```


<br/>
<br/>

### Colours ...
 
```{r}
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
```

```{r}
gg_color_hue(2)
```



<br/>
<br/>



```{r}
getwd()
```








```{r warning=FALSE, fig.width=16, fig.height=8}
vel_thresh <- 1
wind <- 600
p1 <- all_rawdata %>% 
  filter(genotype != "CS") %>% 
  group_by(unique_fly) %>% 
  summarise(genotype = unique(genotype),
            velocity = 100*sum(vel__mmpers[which.max(SmoothedCourtship):ifelse(which.max(SmoothedCopulation) > which.max(SmoothedCourtship),
                                                                                 ifelse(which.max(SmoothedCopulation) <= (which.max(SmoothedCourtship)+(25*wind)), 
                                                                                        which.max(SmoothedCopulation), 
                                                                                        min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                        ),
                                                                                  min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                  )
                                             ]>(vel_thresh),
                                 na.rm = TRUE)/
                                 length(Frame[which.max(SmoothedCourtship):ifelse(which.max(SmoothedCopulation) > which.max(SmoothedCourtship),
                                                                                 ifelse(which.max(SmoothedCopulation) <= (which.max(SmoothedCourtship)+(25*wind)), 
                                                                                        which.max(SmoothedCopulation), 
                                                                                        min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                        ),
                                                                                  min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                  )
                                             ]
                     )) %>% 
  ggplot(aes(x=genotype,y=velocity)) +
    geom_boxplot()
p2 <- all_rawdata %>% 
  filter(genotype != "CS") %>% 
  filter(facing_angle__rad < 35*pi/180) %>% 
  group_by(unique_fly) %>% 
  summarise(genotype = unique(genotype),
            velocity = 100*sum(vel__mmpers[which.max(SmoothedCourtship):ifelse(which.max(SmoothedCopulation) > which.max(SmoothedCourtship),
                                                                                 ifelse(which.max(SmoothedCopulation) <= (which.max(SmoothedCourtship)+(25*wind)), 
                                                                                        which.max(SmoothedCopulation), 
                                                                                        min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                        ),
                                                                                  min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                  )
                                             ]>(vel_thresh),
                                 na.rm = TRUE)/
                                 length(Frame[which.max(SmoothedCourtship):ifelse(which.max(SmoothedCopulation) > which.max(SmoothedCourtship),
                                                                                 ifelse(which.max(SmoothedCopulation) <= (which.max(SmoothedCourtship)+(25*wind)), 
                                                                                        which.max(SmoothedCopulation), 
                                                                                        min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                        ),
                                                                                  min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                  )
                                             ]
                     )) %>%
  ggplot(aes(x=genotype,y=velocity)) +
    geom_boxplot()
p3 <- all_rawdata %>% 
  filter(genotype != "CS") %>% 
  filter(facing_angle__rad > 35*pi/180) %>% 
  group_by(unique_fly) %>% 
  summarise(genotype = unique(genotype),
            velocity = 100*sum(vel__mmpers[which.max(SmoothedCourtship):ifelse(which.max(SmoothedCopulation) > which.max(SmoothedCourtship),
                                                                                 ifelse(which.max(SmoothedCopulation) <= (which.max(SmoothedCourtship)+(25*wind)), 
                                                                                        which.max(SmoothedCopulation), 
                                                                                        min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                        ),
                                                                                  min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                  )
                                             ]>(vel_thresh),
                                 na.rm = TRUE)/
                                 length(Frame[which.max(SmoothedCourtship):ifelse(which.max(SmoothedCopulation) > which.max(SmoothedCourtship),
                                                                                 ifelse(which.max(SmoothedCopulation) <= (which.max(SmoothedCourtship)+(25*wind)), 
                                                                                        which.max(SmoothedCopulation), 
                                                                                        min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                        ),
                                                                                  min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                  )
                                             ]
                     )) %>%
  ggplot(aes(x=genotype,y=velocity)) +
    geom_boxplot()


ggarrange(plotlist = list(p1,p2,p3),
          labels = c("all frames","<35deg facing",">35deg facing"),
          hjust = -0.6,
          vjust = 2,
          ncol = 3,
          nrow = 1)
```











```{r warning=FALSE, fig.width=16, fig.height=4}
all_rawdata %>% 
  filter(FileName == "Megan-2019_03_06_Courtship-DsxVglutTNT_Male_1234_2") %>% 
  filter(Id == 35) %>%
  mutate(rollavg_dist_to_other = rollmean(dist_to_other__mm, 200, fill = c(NA,0,NA), align = c("center"))) %>% 
  ggplot(aes(x=Frame)) +
    geom_point(aes(y=dist_to_other__mm,color=gg_color_hue(2)[1]))+
    geom_point(aes(y=rollavg_dist_to_other,color=gg_color_hue(2)[2]),size=1)
```



```{r warning=FALSE, fig.width=16, fig.height=4}
all_rawdata %>% 
  filter(FileName == "Megan-2019_03_06_Courtship-DsxVglutTNT_Male_1234_6") %>% 
  filter(Id == 7) %>%
  slice(which.max(SmoothedCourtship):ifelse(which.max(SmoothedCopulation) > which.max(SmoothedCourtship),
                                             ifelse(which.max(SmoothedCopulation) <= (which.max(SmoothedCourtship)+(25*600)),
                                                    which.max(SmoothedCopulation),
                                                    min((which.max(SmoothedCourtship)+(25*600)),max(Frame))
                                                    ),
                                              min((which.max(SmoothedCourtship)+(25*600)),max(Frame))
                                              )) %>%
  ggplot(aes(x=Frame)) +
    geom_point(aes(y=vel__mmpers, color=gg_color_hue(2)[1])) +
    geom_point(aes(y=rollmean(vel__mmpers, 20, fill = c(NA,0,NA), align = c("center")),color=gg_color_hue(2)[2]),size=1) +
    geom_point(aes(y=c(ifelse(Approaching==1,Approaching+44,Approaching-2)))) +
    #geom_point(aes(y=c(ifelse(WingGesture==1,WingGesture+0.6,WingGesture-1)))) +
  ylim(0,50)
```







```{r warning=FALSE, fig.width=16, fig.height=4}
all_rawdata %>% 
  filter(FileName == "Megan-2019_03_06_Courtship-DsxVglutTNT_Male_1234_2") %>% 
  filter(Id == 36) %>%
  slice(which.max(SmoothedCourtship):which.max(SmoothedCopulation)) %>% 
  ggplot(aes(x=Frame)) +
    geom_point(aes(y=vel__mmpers, color=gg_color_hue(2)[1])) +
    geom_point(aes(y=rollmean(vel__mmpers, 20, fill = c(NA,0,NA), align = c("center")),color=gg_color_hue(2)[2]),size=1) +
    geom_point(aes(y=c(ifelse(Approaching==1,Approaching+44,Approaching-2)))) +
    #geom_point(aes(y=c(ifelse(WingGesture==1,WingGesture+0.6,WingGesture-1)))) +
    ylim(0,50)
```

















```{r}
all_rawdata %>% 
  filter(genotype != "CS") %>% 
  group_by(unique_fly) %>% 
  summarise(genotype = unique(genotype),
            distance_travelled = sum(vel__mmpers[which.max(SmoothedCourtship):ifelse(which.max(SmoothedCopulation) > which.max(SmoothedCourtship),
                                                                                 ifelse(which.max(SmoothedCopulation) <= (which.max(SmoothedCourtship)+(25*wind)), 
                                                                                        which.max(SmoothedCopulation), 
                                                                                        min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                        ),
                                                                                  min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                  )
                                             ],
                                 na.rm = TRUE)/(25*1000)
            ) %>% 
  ggplot(aes(x=genotype,y=distance_travelled)) +
    geom_boxplot()
```







```{r}
all_rawdata %>% 
  filter(genotype != "CS") %>% 
  group_by(unique_fly) %>% 
  summarise(genotype = unique(genotype),
            distance_travelled = sum(vel__mmpers,
                                 na.rm = TRUE)/(25*1000)
            ) %>% 
  ggplot(aes(x=genotype,y=distance_travelled)) +
    geom_boxplot() +
    ylim(0,10)
```







```{r}
all_rawdata %>% 
  filter(sex == "female") %>% 
  filter(!is.na(treatment)) %>% 
  group_by(unique_fly) %>% 
  summarise(treatment = unique(treatment),
            distance_travelled = sum(vel__mmpers,
                                 na.rm = TRUE)/(25*1000)
            ) %>% 
  ggplot(aes(x=treatment,y=distance_travelled)) +
    geom_boxplot() +
    ylim(0,10)
```



















# **Wing vacillation**



```{r}
temp <- all_rawdata %>% 
  filter(FileName == "Megan-2019_03_06_Courtship-DsxVglutTNT_Male_1234_2") %>% 
  filter(Id == 36) %>% 
  mutate(bin_right_wing = if_else(wing_r_ang__rad>(35*pi/180),1,0),
         bin_left_wing = if_else(wing_l_ang__rad<(-35*pi/180),1,0)
         )
temp$bin_right_wing <- temp$bin_right_wing %>% replace_na(0)
temp$bin_left_wing <- temp$bin_left_wing %>% replace_na(0)
```

```{r}
which.max(temp$SmoothedCourtship)
which.max(temp$SmoothedCopulation)  
  
  
  ifelse(which.max(SmoothedCopulation) > which.max(SmoothedCourtship),
                                                                               ifelse(which.max(SmoothedCopulation) <= (which.max(SmoothedCourtship)+(25*wind)), 
                                                                                      which.max(SmoothedCopulation), 
                                                                                      min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                      ),
                                                                                min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                )
        )
```


```{r}
rwbouts <- rle(temp$bin_right_wing)
rwbouts
```




```{r}
lwbouts <- rle(temp$bin_left_wing)
lwbouts
```




```{r}
ind <- 5
sum(lwbouts$lengths[1:ind])
```



```{r}
min(which(v > 100))
```

```{r}
#frame_at_end_of_bout
rwends <- as.numeric()
for (i in seq(1,length(which(rwbouts$values==1)),1)) {
    rwends[i] = sum(rwbouts$lengths[1:(i*2)])
}
#rwends
lwends <- as.numeric()
for (i in seq(1,length(which(lwbouts$values==1)),1)) {
    lwends[i] = sum(lwbouts$lengths[1:(i*2)])
}
#lwends
```


```{r}
ind <- 2
rwends[ind]
min(which(lwends > rwends[ind]))
lwends[min(which(lwends > rwends[ind]))]
rwends[ind+1]<lwends[min(which(lwends > rwends[ind]))]
```


```{r}
rw_rw <- 0
rw_lw <- 0
for (ind in 1:(length(rwends)-1)) {
  if (rwends[ind+1]<lwends[min(which(lwends > rwends[ind]))]) {
    rw_rw = rw_rw + 1
  } else {
    rw_lw = rw_lw + 1
  }
}
rw_rw
rw_lw

lw_lw <- 0
lw_rw <- 0
for (ind in 1:(length(lwends)-1)) {
  if (lwends[ind+1]<rwends[min(which(rwends > lwends[ind]))]) {
    lw_lw = lw_lw + 1
  } else {
    lw_rw = lw_rw + 1
  }
}
lw_lw
lw_rw
```



```{r}

same_wing <- rw_rw + lw_lw
diff_wing <- rw_lw + lw_rw

same_wing
diff_wing
same_wing/diff_wing


```


```{r}
wind <- 600

temp2 <- all_rawdata %>% 
  filter(FileName == "Megan-2019_03_06_Courtship-DsxVglutTNT_Male_1234_2") %>% 
  filter(Id == 36) %>% 
  slice(which.max(SmoothedCourtship):ifelse(which.max(SmoothedCopulation) > which.max(SmoothedCourtship),
                                                                               ifelse(which.max(SmoothedCopulation) <= (which.max(SmoothedCourtship)+(25*wind)), 
                                                                                      which.max(SmoothedCopulation), 
                                                                                      min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                      ),
                                                                                min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                )
        ) %>% 
  mutate(bin_right_wing = if_else(wing_r_ang__rad>(35*pi/180),1,0),
         bin_left_wing = if_else(wing_l_ang__rad<(-35*pi/180),1,0)
         )
temp2$bin_right_wing <- temp2$bin_right_wing %>% replace_na(0)
temp2$bin_left_wing <- temp2$bin_left_wing %>% replace_na(0)

rwbouts <- rle(temp2$bin_right_wing)
lwbouts <- rle(temp2$bin_left_wing)

rwends <- as.numeric()
for (i in seq(1,length(which(rwbouts$values==1)),1)) {
    rwends[i] = sum(rwbouts$lengths[1:(i*2)])
}
lwends <- as.numeric()
for (i in seq(1,length(which(lwbouts$values==1)),1)) {
    lwends[i] = sum(lwbouts$lengths[1:(i*2)])
}
rw_rw <- 0
rw_lw <- 0
for (ind in 1:(length(rwends)-1)) {
  if (!is_empty(which(lwends > rwends[ind]))) {
    if (rwends[ind+1]<lwends[min(which(lwends > rwends[ind]))]) {
      rw_rw = rw_rw + 1
    } else {
      rw_lw = rw_lw + 1
    }
  }
}
lw_lw <- 0
lw_rw <- 0
for (ind in 1:(length(lwends)-1)) {
  if (!is_empty(which(lwends > rwends[ind]))) {
    if (lwends[ind+1]<rwends[min(which(rwends > lwends[ind]))]) {
      lw_lw = lw_lw + 1
    } else {
      lw_rw = lw_rw + 1
    }
  }
}
genotype = unique(temp2$genotype)
uni_id = unique(temp2$unique_fly)

temp_tibble <- tibble(unique_fly = uni_id,
                      genotype = genotype,
                      same_wing = rw_rw + lw_lw,
                      diff_wing = rw_lw + lw_rw
                      )
wing_vacillation <- bind_rows(wing_vacillation,temp_tibble)

wing_vacillation
```


```{r}
rw_rw <- 0
rw_lw <- 0
for (ind in 1:(length(rwends)-1)) {
  if (rwends[ind+1]<lwends[min(which(lwends > rwends[ind]))]) {
    rw_rw = rw_rw + 1
  } else {
    rw_lw = rw_lw + 1
  }
}
```

```{r}
rwends[ind+1]
lwends[min(which(lwends > rwends[ind]))]
rwends[ind]
min(which(lwends > rwends[ind]))
which(lwends > rwends[ind])
is_empty(which(lwends > rwends[ind]))
!is_empty(which(lwends > rwends[ind]))
```


```{r}
rwbouts <- rle(temp2$bin_right_wing)
rwbouts
length(which(rwbouts$values==1))
```





```{r}
wind <- 600
wing_thresh <- 35

temp <- all_rawdata %>% 
  filter(sex == "male")

uniq_fly <- unique(temp$unique_fly)
wing_vacillation <- tibble()


for (fly in uniq_fly) {
  temp2 <- temp %>% 
    filter(unique_fly == fly) %>% 
    slice(which.max(SmoothedCourtship):ifelse(which.max(SmoothedCopulation) > which.max(SmoothedCourtship),
                                                                                 ifelse(which.max(SmoothedCopulation) <= (which.max(SmoothedCourtship)+(25*wind)), 
                                                                                        which.max(SmoothedCopulation), 
                                                                                        min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                        ),
                                                                                  min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                  )
          ) %>% 
    mutate(bin_right_wing = if_else(wing_r_ang__rad>(wing_thresh*pi/180),1,0),
           bin_left_wing = if_else(wing_l_ang__rad<(-wing_thresh*pi/180),1,0)
           )
  temp2$bin_right_wing <- temp2$bin_right_wing %>% replace_na(0)
  temp2$bin_left_wing <- temp2$bin_left_wing %>% replace_na(0)

  rwbouts <- rle(temp2$bin_right_wing)
  lwbouts <- rle(temp2$bin_left_wing)

  rwends <- as.numeric()
  for (i in seq(1,length(which(rwbouts$values==1)),1)) {
      rwends[i] = sum(rwbouts$lengths[1:(i*2)])
  }
  lwends <- as.numeric()
  for (i in seq(1,length(which(lwbouts$values==1)),1)) {
      lwends[i] = sum(lwbouts$lengths[1:(i*2)])
  }
  rw_rw <- 0
  rw_lw <- 0
  for (ind in 1:(length(rwends)-1)) {
    if (!is_empty(which(lwends > rwends[ind]))) {
      if (rwends[ind+1]<lwends[min(which(lwends > rwends[ind]))]) {
        rw_rw = rw_rw + 1
      } else {
        rw_lw = rw_lw + 1
      }
    }
  }
  lw_lw <- 0
  lw_rw <- 0
  for (ind in 1:(length(lwends)-1)) {
    if (!is_empty(which(rwends > lwends[ind]))) {
      if (lwends[ind+1]<rwends[min(which(rwends > lwends[ind]))]) {
        lw_lw = lw_lw + 1
      } else {
        lw_rw = lw_rw + 1
      }
    }
  }
  genotype = unique(temp2$genotype)
  uni_id = unique(temp2$unique_fly)
  
  temp_tibble <- tibble(unique_fly = uni_id,
                        genotype = genotype,
                        same_wing = rw_rw + lw_lw,
                        diff_wing = rw_lw + lw_rw
                        )
  wing_vacillation <- bind_rows(wing_vacillation,temp_tibble)
}
wing_vacillation
```






```{r}
wing_vacillation %>%
  ggplot(aes(x=genotype,y=same_wing/diff_wing)) + 
    geom_boxplot()
```




```{r}
wing_vacillation %>%
  ggplot(aes(x=genotype,y=same_wing/diff_wing)) + 
    geom_boxplot() +
    ylim(0,10)
```



























```{r}
wind <- 600
wing_thresh <- 35

temp <- all_rawdata %>% 
  filter(sex == "male")

uniq_fly <- unique(temp$unique_fly)
wing_vacillation <- tibble()


for (fly in uniq_fly) {
  temp2 <- temp %>% 
    filter(unique_fly == fly) %>% 
    slice(which.max(SmoothedCourtship):ifelse(which.max(SmoothedCopulation) > which.max(SmoothedCourtship),
                                                                                 ifelse(which.max(SmoothedCopulation) <= (which.max(SmoothedCourtship)+(25*wind)), 
                                                                                        which.max(SmoothedCopulation), 
                                                                                        min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                        ),
                                                                                  min((which.max(SmoothedCourtship)+(25*wind)),max(Frame))
                                                                                  )
          ) %>% 
    mutate(bin_right_wing = if_else(abs(ipsi_wing_ang)>(wing_thresh*pi/180),1,0),
           bin_left_wing = if_else(-abs(contra_wing_ang)<(-wing_thresh*pi/180),1,0)
           )
  temp2$bin_right_wing <- temp2$bin_right_wing %>% replace_na(0)
  temp2$bin_left_wing <- temp2$bin_left_wing %>% replace_na(0)

  rwbouts <- rle(temp2$bin_right_wing)
  lwbouts <- rle(temp2$bin_left_wing)

  rwends <- as.numeric()
  for (i in seq(1,length(which(rwbouts$values==1)),1)) {
      rwends[i] = sum(rwbouts$lengths[1:(i*2)])
  }
  lwends <- as.numeric()
  for (i in seq(1,length(which(lwbouts$values==1)),1)) {
      lwends[i] = sum(lwbouts$lengths[1:(i*2)])
  }
  rw_rw <- 0
  rw_lw <- 0
  for (ind in 1:(length(rwends)-1)) {
    if (!is_empty(which(lwends > rwends[ind]))) {
      if (rwends[ind+1]<lwends[min(which(lwends > rwends[ind]))]) {
        rw_rw = rw_rw + 1
      } else {
        rw_lw = rw_lw + 1
      }
    }
  }
  lw_lw <- 0
  lw_rw <- 0
  for (ind in 1:(length(lwends)-1)) {
    if (!is_empty(which(rwends > lwends[ind]))) {
      if (lwends[ind+1]<rwends[min(which(rwends > lwends[ind]))]) {
        lw_lw = lw_lw + 1
      } else {
        lw_rw = lw_rw + 1
      }
    }
  }
  genotype = unique(temp2$genotype)
  uni_id = unique(temp2$unique_fly)
  
  temp_tibble <- tibble(unique_fly = uni_id,
                        genotype = genotype,
                        next_ipsi = rw_rw + lw_rw,
                        next_contra = rw_lw + lw_lw
                        )
  wing_vacillation <- bind_rows(wing_vacillation,temp_tibble)
}
wing_vacillation
```








```{r}
wing_vacillation %>%
  ggplot(aes(x=genotype,y=next_ipsi/next_contra)) + 
    geom_boxplot()
```




```{r}
wing_vacillation %>%
  ggplot(aes(x=genotype,y=next_ipsi/next_contra)) + 
    geom_boxplot() +
    ylim(0,4)
```



















































































